import { chunkFile } from "./chunker.js"
import { extractStructuredFacts } from "./facts.js"
import { createCommentChunks } from "./comments.js"
import type { CodeChunk } from "./chunker.js"
import type { SourceFile } from "./files.js"

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function makeFile(path: string, content: string): SourceFile {
  return { absolutePath: path, relativePath: path, content }
}

function runTests(): void {
  console.log("Running chunker tests...")

  testTsFunctionSplit()
  testTsClassMethodSplit()
  testPhpFunctionSplit()
  testSqlStatementSplit()
  testMarkdownH2Split()
  testNoiseFilterCss()
  testNoiseFilterAutoGenerated()
  testMinSizeEnforcement()
  testOverlapCorrectness()
  testFactsSkipComments()
  testCommentChunksFilterNoise()

  console.log("All chunker tests passed!")
}

function testTsFunctionSplit(): void {
  console.log("Test: TS function split")
  const file = makeFile("src/handler.ts", [
    "import { Router, Request, Response } from 'express'",
    "",
    "export async function getUser(req: Request, res: Response) {",
    "  const id = req.params.id",
    "  const user = await db.user.findUnique({ where: { id } })",
    "  if (!user) return res.status(404).json({ error: 'Not found' })",
    "  return res.json({ id: user.id, name: user.name })",
    "}",
    "",
    "export async function createUser(req: Request, res: Response) {",
    "  const body = req.body",
    "  const user = await db.user.create({ data: body })",
    "  if (!user) return res.status(500).json({ error: 'Create failed' })",
    "  return res.json({ created: true, id: user.id })",
    "}",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "api", "main", "abc123")
  assert(chunks.length >= 2, `Expected >=2 chunks, got ${chunks.length}`)
  const fn1 = chunks.find(c => c.symbolName === "getUser")
  assert(fn1 !== undefined, "getUser chunk should exist")
  assert(fn1!.chunkType === "function", `chunkType should be function, got ${fn1!.chunkType}`)
  assert(fn1!.content.includes("getUser"), "Content should include function name")
  const fn2 = chunks.find(c => c.symbolName === "createUser")
  assert(fn2 !== undefined, "createUser chunk should exist")
  console.log("  passed")
}

function testTsClassMethodSplit(): void {
  console.log("Test: TS class + method split")
  const file = makeFile("src/service.ts", [
    "export class UserService {",
    "  async findById(id: string) {",
    "    const user = await db.user.findUnique({ where: { id } })",
    "    if (!user) throw new NotFoundError('User not found')",
    "    return { id: user.id, name: user.name, email: user.email }",
    "  }",
    "",
    "  async create(data: CreateUserDto) {",
    "    const validated = await validateCreateUser(data)",
    "    const user = await db.user.create({ data: validated })",
    "    return { created: true, id: user.id, name: user.name }",
    "  }",
    "}",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "api", "main", "abc123")
  const methodChunks = chunks.filter(c => c.chunkType === "method")
  assert(methodChunks.length >= 2, `Expected >=2 methods, got ${methodChunks.length}`)
  assert(methodChunks.some(c => c.symbolName === "findById"), "findById method should exist")
  assert(methodChunks.some(c => c.symbolName === "create"), "create method should exist")
  methodChunks.forEach(c => assert(c.parentSymbol === "UserService", `parentSymbol should be UserService, got ${c.parentSymbol}`))
  console.log("  passed")
}

function testPhpFunctionSplit(): void {
  console.log("Test: PHP function split")
  const file = makeFile("src/handler.php", [
    "<?php",
    "function get_user($id) {",
    "  $db = new PDO($dsn, $user, $pass);",
    "  $stmt = $db->prepare('SELECT * FROM users WHERE id = :id');",
    "  $stmt->execute([':id' => $id]);",
    "  return $stmt->fetch(PDO::FETCH_ASSOC);",
    "}",
    "",
    "class UserController {",
    "  public function show($id) {",
    "    $user = $this->get_user($id);",
    "    if (!$user) {",
    "      http_response_code(404);",
    "      echo json_encode(['error' => 'User not found']);",
    "      return;",
    "    }",
    "    echo json_encode($user);",
    "  }",
    "}",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "api", "main", "abc123")
  const fnChunk = chunks.find(c => c.symbolName === "get_user")
  assert(fnChunk !== undefined, "get_user function chunk should exist")
  const methodChunk = chunks.find(c => c.chunkType === "method" && c.symbolName === "show")
  assert(methodChunk !== undefined, "show method chunk should exist")
  console.log("  passed")
}

function testSqlStatementSplit(): void {
  console.log("Test: SQL statement split")
  const file = makeFile("migrations/001.sql", [
    "-- Create users table",
    "CREATE TABLE users (",
    "  id INT PRIMARY KEY,",
    "  name VARCHAR(255)",
    ");",
    "",
    "-- Create orders table",
    "CREATE TABLE orders (",
    "  id INT PRIMARY KEY,",
    "  user_id INT REFERENCES users(id)",
    ");",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  assert(chunks.length >= 2, `Expected >=2 statements, got ${chunks.length}`)
  const createUsers = chunks.find(c => c.content.includes("CREATE TABLE users"))
  assert(createUsers !== undefined, "users table chunk should exist")
  const createOrders = chunks.find(c => c.content.includes("CREATE TABLE orders"))
  assert(createOrders !== undefined, "orders table chunk should exist")
  console.log("  passed")
}

function testMarkdownH2Split(): void {
  console.log("Test: Markdown H2 split")
  const file = makeFile("docs/guide.md", [
    "# Guide",
    "",
    "Intro paragraph here.",
    "",
    "## Installation",
    "",
    "Run npm install.",
    "",
    "## Usage",
    "",
    "Import and call the function.",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  assert(chunks.length >= 2, `Expected >=2 sections, got ${chunks.length}`)
  const installChunk = chunks.find(c => c.content.includes("Installation"))
  assert(installChunk !== undefined, "Installation section should exist")
  const usageChunk = chunks.find(c => c.content.includes("Usage"))
  assert(usageChunk !== undefined, "Usage section should exist")
  console.log("  passed")
}

function testNoiseFilterCss(): void {
  console.log("Test: noise filter — CSS value")
  const file = makeFile("template/style.php", [
    "<style>",
    "  .btn { color: #ffcc00 !important; }",
    "  .btn { margin: 0; }",
    "</style>",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  const cssNoise = chunks.find(c => c.content.trim().match(/^#[0-9a-f]{3,8}\s*!important/i))
  assert(cssNoise === undefined, "CSS hex color noise should be filtered")
  console.log("  passed")
}

function testNoiseFilterAutoGenerated(): void {
  console.log("Test: noise filter — auto-generated boilerplate")
  const file = makeFile("sdk/generated.ts", [
    "// This file was auto-generated from sdk-root/src/data/config.json",
    "// Do not edit this file manually",
    "export const config = {",
    "  endpoint: 'https://api.example.com',",
    "  timeout: 5000,",
    "  retries: 3,",
    "  apiKey: process.env.API_KEY,",
    "  debug: false,",
    "}",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  const autoGen = chunks.find(c => /auto-generated/i.test(c.content) && c.content.trim().startsWith("//"))
  assert(autoGen === undefined, "Auto-generated comment chunk should be filtered")
  const configChunk = chunks.find(c => c.content.includes("endpoint"))
  assert(configChunk !== undefined, "Config export chunk should survive")
  console.log("  passed")
}

function testMinSizeEnforcement(): void {
  console.log("Test: min size enforcement")
  const file = makeFile("tiny.ts", "const x = 1;\n")
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  assert(chunks.length === 0, `Expected 0 chunks for tiny file, got ${chunks.length}`)
  console.log("  passed")
}

function testOverlapCorrectness(): void {
  console.log("Test: overlap correctness")
  const file = makeFile("multi.ts", [
    "function first() {",
    "  return 1",
    "}",
    "",
    "function second() {",
    "  return 2",
    "}",
  ].join("\n"))
  const chunks = chunkFile(file, "test-repo", "library", "main", "abc123")
  const secondChunk = chunks.find(c => c.symbolName === "second")
  if (secondChunk) {
    assert(secondChunk.hasOverlap === true, "Second chunk should have overlap")
  }
  console.log("  passed")
}

function testFactsSkipComments(): void {
  console.log("Test: facts skip comment lines")
  const content = [
    "// This file was auto-generated from sdk-root/data.json",
    "const config = process.env.DB_HOST || 'localhost'",
    "/* SELECT * FROM users WHERE active = 1 */",
    "export const PORT = 3000",
  ].join("\n")
  const facts = extractStructuredFacts(content, 1)
  const commentFact = facts.find(f => f.text.trim().startsWith("//"))
  assert(commentFact === undefined, "Comment line should not produce a fact")
  const blockCommentFact = facts.find(f => f.text.trim().startsWith("/*"))
  assert(blockCommentFact === undefined, "Block comment line should not produce a fact")
  const envFact = facts.find(f => f.category === "config" && f.text.includes("process.env"))
  assert(envFact !== undefined, "process.env line should produce config fact")
  console.log("  passed")
}

function testCommentChunksFilterNoise(): void {
  console.log("Test: comment chunks filter noise")
  const content = [
    "<?php",
    "// This is a real comment about the function below",
    "// TODO: refactor this later",
    "function handler() { return true; }",
    "// #ffcc00",
    "// auto-generated by tool",
    "/* margin: 0; */",
    "",
    "/**",
    " * JSDoc: This function handles user authentication.",
    " * @param {string} token - JWT token",
    " */",
    "function auth(token) { return token }",
  ].join("\n")
  const chunks = createCommentChunks("test.php", content, "test-repo", "api", "main", "abc123")
  assert(chunks.length > 0, `Expected some comment chunks, got ${chunks.length}`)
  const cssNoise = chunks.find(c => /#ffcc00|margin:\s*0/i.test(c.content))
  assert(cssNoise === undefined, "CSS noise comment should be filtered")
  const autoGen = chunks.find(c => /auto-generated/i.test(c.content))
  assert(autoGen === undefined, "Auto-generated comment should be filtered")
  const jsdoc = chunks.find(c => /JSDoc|authentication/i.test(c.content))
  assert(jsdoc !== undefined, "JSDoc comment should survive")
  const todo = chunks.find(c => /TODO/i.test(c.content))
  assert(todo !== undefined, "TODO comment should survive")
  console.log("  passed")
}

export { runTests }

runTests()
