import type { PackageFacts, EnvVarFact, ConfigDefaultFact, ApiRouteFact, RabbitMqFact, DatabaseFact } from '../types.js';

export interface OverviewInput {
  packageFacts: PackageFacts[];
  envFacts: EnvVarFact[];
  configDefaultFacts?: ConfigDefaultFact[];
  apiRouteFacts: ApiRouteFact[];
  rabbitMqFacts: RabbitMqFact[];
  databaseFacts: DatabaseFact[];
  timestamp?: boolean;
}

/**
 * Generates overview.md as the entry point for all generated docs.
 */
export function generateOverviewMarkdown(input: OverviewInput): string {
  const lines: string[] = [];

  lines.push('# Repository Overview');
  lines.push('');

  if (input.timestamp) {
    lines.push(`> Generated at: ${new Date().toISOString()}`);
    lines.push('');
  }

  lines.push('This documentation was auto-generated by Repo Doctor using static analysis only.');
  lines.push('');

  // Counts
  const serviceCount = input.packageFacts.length;
  const envCount = input.envFacts.length;
  const configDefaultCount = input.configDefaultFacts?.length ?? 0;
  const apiCount = input.apiRouteFacts.length;
  const mqCount = input.rabbitMqFacts.length;
  const dbCount = input.databaseFacts.length;

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Services (package.json) | ${serviceCount} |`);
  lines.push(`| Environment variables | ${envCount} |`);
  lines.push(`| Configuration defaults | ${configDefaultCount} |`);
  lines.push(`| API routes | ${apiCount} |`);
  lines.push(`| RabbitMQ usages | ${mqCount} |`);
  lines.push(`| Database usages | ${dbCount} |`);
  lines.push('');

  // Links
  lines.push('## Generated Documents');
  lines.push('');
  lines.push('- [config.md](./config.md) - Environment-backed configuration defaults');
  lines.push('- [services.md](./services.md) — Package metadata and dependencies');
  lines.push('- [env.md](./env.md) — Environment variables detected in source');
  lines.push('- [api.md](./api.md) — HTTP API routes');
  lines.push('- [rabbitmq.md](./rabbitmq.md) — RabbitMQ queues, exchanges, and messaging');
  lines.push('- [database.md](./database.md) — SQL tables, TypeORM entities, and repositories');
  lines.push('- [architecture.md](./architecture.md) — Mermaid architecture diagrams');
  lines.push('');

  // Limitations
  lines.push('## Limitations');
  lines.push('');
  lines.push('- Static analysis only — no runtime or dynamic behavior is captured.');
  lines.push('- Regex-based extraction — complex or indirect patterns may be missed.');
  lines.push('- No cross-service resolution — relationships are per-repository.');
  lines.push('- Confidence labels indicate extraction certainty, not code correctness.');
  lines.push('- Results should be verified against source code.');
  lines.push('');

  return lines.join('\n');
}
